name: generate and commit table data

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetches all history for .git/shallow update

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Set the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python get_model_table.py

    - name: Commit and push if changes
      uses: stefanzweifel/git-auto-commit-action@v5
